name: Build and Deploy Code

on: [push, pull_request]
  # or
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     -"test_branch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to Ashish
        run: echo "hello Ashish"